<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/jquery.dataTables.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery.dataTables.js')
            ->prependFile($this->basePath() . '/js/jquery.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')                
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/bootstrap.js')   
        ; ?>
        <script type="text/javascript" language="javascript">
            $(document).ready(function() {
            $('#tablarol').dataTable();
                    } );
        </script>
    </head>
    <body>
              <!--barra de navegacion-->
      <nav class="navbar navbar-inverse" role="navigation">
       <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<?php echo $this->BasePath().'/admin/index/index' ?>">Admin</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuarios<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Nuevo</a></li>
                <li><a href="#">Listar</a></li>
                <li class="divider"></li>
                <li><a href="#">Reportes</a></li>
              </ul>
            </li>
            
           <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Rol<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Nuevo</a></li>
                <li><a href="<?php echo $this->basePath().'/admin/rol/listar' ?>">Listar</a></li>
                <li class="divider"></li>
                <li><a href="#">Reportes</a></li>
              </ul>
            </li>
            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sucursales<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Nueva Sucursal</a></li>
                <li><a href="#">Listar</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->basePath().'/cliente/index/index' ?>">Ir a Cliente</a></li>
              </ul>
            </li>

          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
     </nav>
        <div class="container">       
               <?php echo $this->content; ?>
        </div>    
   
    </body>
</html>
